// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Prisma CLI config (Prisma v7 compatible in your setup)
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
